#!/usr/bin/env sh

set -e

build_output="$(dotnet build --no-restore --nologo --verbosity quiet -clp:NoSummary 2>&1)" || {
  pretty_errors="$(
    echo "$build_output" |
      awk '/: error [A-Z]+[0-9]+:/ && !seen[$0]++' |
      sed -nE 's#^(.*/)?(src|tests)/([^:]+)\(([0-9]+),([0-9]+)\): error ([A-Z]+[0-9]+): (.*) \[.*\]$#✗ \6 \2/\3:\4:\5\
  \7#p'
  )"

  if [ -n "$pretty_errors" ]; then
    echo "$pretty_errors"
  else
    echo "$build_output"
  fi

  exit 1
}